# Generated by Django 5.2.9 on 2026-03-24 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_CART', 'In Cart'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='IN_CART', max_length=20)),
                ('booking_type', models.CharField(choices=[('TRAIN_TICKET', 'Train Ticket'), ('ACCOMMODATION', 'Accommodation')], max_length=20)),
                ('price_rp', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_location', models.CharField(blank=True, max_length=255, null=True)),
                ('to_location', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_time', models.CharField(blank=True, max_length=100, null=True)),
                ('arrival_time', models.CharField(blank=True, max_length=100, null=True)),
                ('train_number', models.CharField(blank=True, max_length=100, null=True)),
                ('carriage', models.CharField(blank=True, max_length=50, null=True)),
                ('seat_number', models.CharField(blank=True, max_length=50, null=True)),
                ('class_label', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('stay_date', models.CharField(blank=True, max_length=100, null=True)),
                ('stay_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('bed_type', models.CharField(blank=True, max_length=100, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('amount_rp', models.IntegerField()),
                ('is_discount', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='bookings.booking')),
            ],
        ),
    ]
