# Generated by Django 5.2.9 on 2026-03-24 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_type',
            new_name='b_type',
        ),
    ]
