# Generated by Django 5.2.9 on 2026-03-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_booking_type_booking_b_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='b_type',
            new_name='booking_type',
        ),
    ]
