# Generated by Django 5.2.9 on 2026-03-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_b_type_booking_booking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('CAR_TICKET', 'Car Ticket'), ('BUS_TICKET', 'Bus Ticket'), ('TRAIN_TICKET', 'Train Ticket'), ('PLANE_TICKET', 'Plane Ticket'), ('ACCOMMODATION', 'Accommodation Ticket')], max_length=20),
        ),
    ]
