# Generated by Django 5.2.9 on 2026-04-03 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_booking_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Villa', 'Villa'), ('Hotel', 'Hotel'), ('Apartment', 'Apartment'), ('Condo', 'Condo')], max_length=50)),
                ('image_url', models.URLField(max_length=500)),
                ('location', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('advantages', models.JSONField(default=list, help_text='Guest Favorites list')),
                ('section_tag', models.CharField(choices=[('Discount', 'Discount'), ('Favorite', 'Favorite'), ('Hot', 'Hot')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinations', models.ManyToManyField(related_name='wishlisted_by', to='bookings.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
