# Generated by Django 5.2.9 on 2026-04-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_destination_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='tags',
            field=models.JSONField(default=list, help_text='Searchable tags like Cozy, Airy'),
        ),
    ]
