# Generated by Django 5.2.9 on 2026-04-11 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_alter_review_thoughts_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.destination'),
        ),
        migrations.AddField(
            model_name='booking',
            name='manual_review_trigger',
            field=models.BooleanField(default=False),
        ),
    ]
