# Generated by Django 5.2.9 on 2026-03-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='code',
            field=models.CharField(default='temp_code', max_length=50),
        ),
    ]
