# Generated by Django 5.2.9 on 2026-04-11 09:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_promotion_discount_value_promotion_min_purchase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='collected_by',
            field=models.ManyToManyField(blank=True, related_name='collected_coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
