# Generated by Django 5.2.9 on 2026-03-24 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_type', models.CharField(blank=True, choices=[('Bugs', 'Bugs'), ('Text Error', 'Text Error'), ('Button Malfunctions', 'Button Malfunctions'), ('Design Error', 'Design Error'), ('Others', 'Others')], max_length=50, null=True)),
                ('location', models.CharField(blank=True, choices=[('Home', 'Home'), ('Chat AI', 'Chat AI'), ('Keranjang', 'Keranjang'), ('Pembayaran', 'Pembayaran'), ('Others', 'Others')], max_length=50, null=True)),
                ('publish_type', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Private', max_length=20)),
                ('header', models.CharField(max_length=255)),
                ('statement', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_attachments/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('solved', 'Solved'), ('replied', 'Replied')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='support.supportticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ticket Replies',
            },
        ),
    ]
