# Generated by Django 5.2.9 on 2026-04-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('GOLD', 'Gold'), ('PREMIUM', 'Premium')], default='FREE', max_length=20),
        ),
    ]
