# Generated by Django 5.2.9 on 2026-03-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_data', '0002_destination_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rideoption',
            name='icon_code_point',
        ),
    ]
