# Generated by Django 5.2.9 on 2026-03-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_data', '0003_remove_rideoption_icon_code_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
